---

- name: Create destination directory
  file:
    path: "{{ maven_destination_directory }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Download and untar the maven binary file
  unarchive:
    src: "{{ maven_bin_url }}"
    dest: "{{ maven_destination_directory }}"
    remote_src: yes
    owner: root
    group: root
    mode: 0755

- name: Set M2_HOME
  template:
    src: maven_home.sh.j2
    dest: /etc/profile.d/maven_home.sh

- name: Create a symlink to mvn
  file:
    src: "{{ maven_destination_directory }}/apache-maven-{{ maven_version }}/bin/mvn"
    dest: /usr/local/bin/mvn
    owner: root
    group: root
    state: link

- name: Get maven bash completion
  get_url:
    url: https://raw.githubusercontent.com/juven/maven-bash-completion/master/bash_completion.bash
    dest: /etc/bash_completion.d/mvn
  when: maven_enable_bash_completion
